package br.com.alura.bytebank.test

import br.com.alura.bytebank.template.Address
//Dessa forma também funciona só que é sempre importante deixar o valor da variável imutável,
//E o try catch dessa forma, não da acesso ao atributo que esta dentro do seu escopo

fun testePilha() {

    println("Inicio main")
    val input: String = "1"

    try {
        val value: Double = input.toDouble() //Conversão
        println("Valor recebido: $value")
    } catch (e: NumberFormatException) {
        println("Problema na conversão")
        e.printStackTrace()
    }

    funcao1()
    println("fim main")


}

fun funcao1() {
    println("inicio função1")
    try {
        funcao2()
    } catch (e: ClassCastException) {
        println(e.message) //Retorna o motivo do lançamento da exception com a justificativa
        println(e.stackTrace) //É um objeto
        println(e.cause) // Causa
        e.printStackTrace()
        println("ClassCastException foi pegada")
    }
    println("fim função1")
}


fun funcao2() {
    println("inicio função2")
    for (i in 1..5) {
        println(i)
        val address = Any()
        address as Address

    }
    println("fim função2")
}